apiVersion: v1
kind: Namespace
metadata:
  name: app-namespace
---
apiVersion: v1
kind: Service
metadata:
  name: backend-db
  namespace: app-namespace
spec:
  selector:
    app: backend-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-db
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-db
  template:
    metadata:
      labels:
        app: backend-db
    spec:
      containers:
        - name: backend-db
          image: henry071190/backend_db
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "pw"
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: app-namespace
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: henry071190/backend
          ports:
            - containerPort: 8888
          env:
            - name: DB_HOST
              value: "backend-db"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: app-namespace
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: henry071190/frontend
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              value: "http://backend-service:8888"
