apiVersion: apps/v1
kind: Deployment
metadata:
  name: usercenter
  labels:
    tier: backend
    app: usercenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usercenter
  template:
    metadata:
      labels:
        tier: backend
        app: usercenter
    spec:
      containers:
      - name: backend
        image: henry071190/usercenter
        ports:
        - containerPort: 8080
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config      # Name of the ConfigMap
                key: USERCENTER_DBHOST  
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-root-password  # Name of the Secret
                key: MYSQL_ROOT_PASSWORD   # Key in the Secret
          - name: SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config      # Name of the ConfigMap
                key: USERCENTER_PORT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe
  labels:
    tier: backend
    app: recipe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe
  template:
    metadata:
      labels:
        tier: backend
        app: recipe
    spec:
      containers:
      - name: recipe
        image: henry071190/recipe
        ports:
        - containerPort: 8081
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config      # Name of the ConfigMap
                key: RECIPE_DBHOST  
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-root-password  # Name of the Secret
                key: MYSQL_ROOT_PASSWORD   # Key in the Secret
          - name: SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config      # Name of the ConfigMap
                key: RECIPE_PORT  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping
  labels:
    tier: backend
    app: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        tier: backend
        app: shopping
    spec:
      containers:
      - name: shopping
        image: henry071190/shopping
        ports:
        - containerPort: 5000
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config      # Name of the ConfigMap
                key: SHOPPING_DBHOST  
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-root-password  # Name of the Secret
                key: MYSQL_ROOT_PASSWORD   # Key in the Secret
          - name: SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config      # Name of the ConfigMap
                key: SHOPPING_PORT  