apiVersion: apps/v1
kind: Deployment
metadata:
  name: usercenter-db
  labels:
    tier: backend
    app: usercenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usercenter-db
  template:
    metadata:
      labels:
        app: usercenter-db
    spec:
      containers:
      - name: usercenter-db
        image: henry071190/usercenter-db:newapp
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-root-password  # Name of the Secret
                key: MYSQL_ROOT_PASSWORD   # Key in the Secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-db
  labels:
    tier: backend
    app: recipe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-db
  template:
    metadata:
      labels:
        app: recipe-db
    spec:
      containers:
      - name: recipe-db
        image: henry071190/recipe-db:newapp
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-root-password  # Name of the Secret
                key: MYSQL_ROOT_PASSWORD   # Key in the Secret